name: tasc
description: "Flutter Application for TASC Admins"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.3
  mesh_gradient: ^1.3.7
  postgres: ^3.4.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  cuid2: ^3.1.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.0
  flutter_advanced_drawer: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/
    - assets/Logo/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/Logo/tasclogo.png"
  adaptive_icon_background: "assets/Logo/tasclogo_background.png"
  adaptive_icon_foreground: "assets/Logo/tasclogo_foreground.png"

flutter_native_splash:
  color: "#ac94d8"
  color_dark: "#301b8e"
  image: "assets/Logo/tasclogo_resized.png"
  image_dark: "assets/Logo/tasclogo_resized.png"

  android_12:
    color: "#ac94d8"
    color_dark: "#301b8e"
    image: "assets/Logo/tasclogo_resized.png"
    image_dark: "assets/Logo/tasclogo_resized.png"