name: tasc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_lints: ^4.0.0
  flutter_animate: ^4.5.0
  vibration: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/
    - assets/Logo/
